language: ruby

rvm:
  - 2.5

cache: bundler -v 2.0.1

before_install:
  - gem update --system
  - gem install bundler -v 2.0.1
  - gem install rubocop -v 0.67.2
  - gem install rspec -v 3.8
  - gem install reek -v 5.4

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake