test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: iwr1
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>
  bucket: iwr

google_dev:
  service: GCS
  project: iwr1
  credentials: <%= Rails.root.join("config/secrets/iwr.json") %>
  bucket: iwr
